export interface Beer {
  id: string
  slug: string
  name: string
  nameBg: string
  style: string
  styleBg: string
  abv: number
  ibu: number | null
  plato: number
  ml: number[]
  serveTemp: string
  glass: string
  hops: string[]
  color: string
  accentHex: string
  contrastHex: string
  displayFont: string
  taglineEn: string
  taglineBg: string
  storyEn: string
  storyBg: string
  pairingEn: string
  pairingBg: string
  format: 'can' | 'keg' | 'both'
  kegSizes: ('20L' | '30L')[]
  seasonal: boolean
  active: boolean
  hasLabel: boolean
  labelSrc?: string
  labelType?: 'image' | 'pdf'
  tags: ('unfiltered' | 'unpasteurised' | 'vegan')[]
  priceB2C?: number
}

export const beers: Beer[] = [
  {
    id: 'lion-heart',
    slug: 'lion-heart',
    name: 'Lion Heart',
    nameBg: 'Lion Heart',
    style: 'New England IPA',
    styleBg: 'Ню Ингланд ИПА',
    abv: 5.5,
    ibu: 45,
    plato: 12.5,
    ml: [330, 500],
    serveTemp: '6–8°C',
    glass: 'Tulip',
    hops: ['Amarillo', 'Mosaic', 'Hallertau Blanc'],
    color: 'Yellow, clear',
    accentHex: '#00ACF0',
    contrastHex: '#0E0E10',
    displayFont: 'Resagokr',
    taglineEn: 'Citrus, clarity and character. The beer everyone orders twice.',
    taglineBg: 'Цитруси, светлина и характер. Бирата, която всички поръчват повторно.',
    storyEn: 'Some beers need explaining. Lion Heart just gets ordered — twice. Amarillo brings orange and grapefruit, Mosaic layers in tropical depth, Hallertau Blanc finishes with white grape and florals. Light on the body, complex on the palate.',
    storyBg: 'Някои бири изискват обяснение. Lion Heart просто се поръчва — два пъти. Amarillo носи портокал и грейпфрут, Mosaic добавя тропическа дълбочина, Hallertau Blanc завършва с бяло грозде и флорални нотки.',
    pairingEn: 'Asian cuisine — Thai curry, sushi, pad thai. Grilled chicken, light cheeses.',
    pairingBg: 'Азиатска кухня — тайско кари, суши, пад тай. Пилешко на скара, леки сирена.',
    format: 'both',
    kegSizes: ['20L', '30L'],
    seasonal: false,
    active: true,
    hasLabel: true,
    labelSrc: '/labels/lion-heart.png',
    labelType: 'image',
    tags: ['unfiltered', 'unpasteurised', 'vegan'],
    priceB2C: 3.20,
  },
  {
    id: 'alma',
    slug: 'alma',
    name: 'Alma',
    nameBg: 'Alma',
    style: 'Vienna Hazy IPA',
    styleBg: 'Виенска хейзи ИПА',
    abv: 5.1,
    ibu: 40,
    plato: 12.4,
    ml: [330],
    serveTemp: '6–8°C',
    glass: 'Tulip',
    hops: ['Centennial', 'Mosaic'],
    color: 'Pale amber',
    accentHex: '#1C4D4A',
    contrastHex: '#D9A441',
    displayFont: 'Yarin',
    taglineEn: 'Classic malt, modern hops. Vienna, reimagined.',
    taglineBg: 'Класически малц, модерни хмелове. Виена, преосмислена.',
    storyEn: 'Vienna malt is an old craft — aromatic, warm, with a delicate sweetness. Centennial and Mosaic are modernists: citrus, tropics, intensity. Alma is where the two worlds meet — structured like a classic IPA, juicy like a contemporary Hazy. Sunset in a glass.',
    storyBg: 'Виенският малц е стар занаят — ароматен, топъл, с деликатна сладост. Centennial и Mosaic са модернисти: цитрус, тропици, интензивност. Alma е там, където двата свята се срещат.',
    pairingEn: 'Mexican cuisine, spiced burgers, aged cheeses.',
    pairingBg: 'Мексиканска кухня, бургери с подправки, зрели сирена.',
    format: 'can',
    kegSizes: [],
    seasonal: true,
    active: true,
    hasLabel: true,
    labelSrc: '/labels/alma.png',
    labelType: 'image',
    tags: ['unfiltered', 'unpasteurised', 'vegan'],
    priceB2C: 3.20,
  },
  {
    id: 'hippy-shake',
    slug: 'hippy-shake',
    name: 'Hippy Shake',
    nameBg: 'Hippy Shake',
    style: 'New England IPA',
    styleBg: 'Ню Ингланд ИПА',
    abv: 6.9,
    ibu: 55,
    plato: 15.5,
    ml: [500],
    serveTemp: '6–8°C',
    glass: 'Tulip',
    hops: ['Mosaic', 'Simcoe', 'Columbus'],
    color: 'Yellow',
    accentHex: '#F5832A',
    contrastHex: '#2A2C72',
    displayFont: 'Caviar Dreams',
    taglineEn: "Bulgaria's first NEIPA. Still unmatched.",
    taglineBg: 'Първата NEIPA в България. Все още незаменима.',
    storyEn: "2017. NEIPA is a new style, barely known in Bulgaria. Hippy Shake changes that — dense, juicy, uncompromising. Mosaic brings blueberry and mango, Simcoe layers in pine and citrus, Columbus closes with depth and backbone. Years later, the recipe hasn't changed, because there's been no reason to.",
    storyBg: '2017 г. NEIPA е нов стил, почти непознат в България. Hippy Shake променя това — гъста, сочна, безкомпромисна.',
    pairingEn: 'Spicy wings, BBQ, cheddar burgers.',
    pairingBg: 'Пикантни крилца, барбекю, бургери с чедър.',
    format: 'both',
    kegSizes: ['20L', '30L'],
    seasonal: false,
    active: true,
    hasLabel: true,
    labelSrc: '/labels/hippy-shake.png',
    labelType: 'image',
    tags: ['unfiltered', 'unpasteurised', 'vegan'],
    priceB2C: 3.40,
  },
  {
    id: 'alexis',
    slug: 'alexis',
    name: 'Alexis',
    nameBg: 'Alexis',
    style: 'Pale Ale',
    styleBg: 'Пейл Ейл',
    abv: 4.9,
    ibu: 30,
    plato: 11.5,
    ml: [500],
    serveTemp: '8–10°C',
    glass: 'Pint',
    hops: ['Simcoe', 'Loral'],
    color: 'Pale yellow',
    accentHex: '#EA236D',
    contrastHex: '#FFC41C',
    displayFont: 'Satellite',
    taglineEn: 'Fresh, light, uncomplicated. A Pale Ale for every occasion.',
    taglineBg: 'Свежа, лека, без излишно. Pale Ale за всеки повод.',
    storyEn: 'Not every beer needs to impress with intensity. Alexis impresses with balance. Simcoe adds light citrus character, Loral brings floral and grassy nuance. Brewed for a birthday, kept for its character.',
    storyBg: 'Не всяка бира трябва да впечатлява с интензивност. Alexis впечатлява с баланс. Simcoe добавя лек цитрусов характер, Loral носи флорална и тревиста нюансировка.',
    pairingEn: 'Salads, grilled fish, light pasta.',
    pairingBg: 'Салати, риба на скара, лека паста.',
    format: 'both',
    kegSizes: ['20L', '30L'],
    seasonal: false,
    active: true,
    hasLabel: true,
    labelSrc: '/labels/alexis.png',
    labelType: 'image',
    tags: ['unfiltered', 'unpasteurised', 'vegan'],
    priceB2C: 2.90,
  },
  {
    id: 'pulpa-fiction',
    slug: 'pulpa-fiction',
    name: 'Pulpa Fiction',
    nameBg: 'Pulpa Fiction',
    style: 'Sour NEIPA',
    styleBg: 'Сауър Ню Ингланд ИПА',
    abv: 7.0,
    ibu: 25,
    plato: 13.8,
    ml: [500],
    serveTemp: '6–8°C',
    glass: 'Tulip',
    hops: ['Centennial', 'Mosaic', 'Hallertau Blanc'],
    color: 'Deep yellow',
    accentHex: '#ED1848',
    contrastHex: '#FFDE02',
    displayFont: 'Koshey',
    taglineEn: 'Sour, fruity, hoppy. All at once.',
    taglineBg: 'Кисело, плодово, хмелено. Всичко наведнъж.',
    storyEn: "Sour and hoppy rarely meet in balance. Pulpa Fiction is the exception — Dorst's first sour (2025). Centennial brings grapefruit and orange, Mosaic layers in tropical depth, Hallertau Blanc finishes with florals, and over it all sits a bright acidity that refreshes rather than dominates.",
    storyBg: 'Кисело и хмелено рядко се срещат в баланс. Pulpa Fiction е изключението — първата кисела бира на Dorst (2025).',
    pairingEn: "Goat's cheese, Thai cuisine, citrus desserts.",
    pairingBg: 'Козе сирене, тайска кухня, цитрусови десерти.',
    format: 'can',
    kegSizes: [],
    seasonal: false,
    active: true,
    hasLabel: true,
    labelSrc: '/labels/pulpa-fiction.pdf',
    labelType: 'pdf',
    tags: ['unfiltered', 'unpasteurised', 'vegan'],
    priceB2C: 3.60,
  },
  {
    id: 'full-breakfast-stout',
    slug: 'full-breakfast-stout',
    name: 'Full Breakfast Stout',
    nameBg: 'Full Breakfast Stout',
    style: 'Imperial Stout',
    styleBg: 'Империален Стаут',
    abv: 9.0,
    ibu: null,
    plato: 24.0,
    ml: [500],
    serveTemp: '8–14°C',
    glass: 'Snifter',
    hops: ['Earthy hops'],
    color: 'Black',
    accentHex: '#5B3A8C',
    contrastHex: '#7BC4A4',
    displayFont: 'Meta',
    taglineEn: 'Sometimes bigger is better.',
    taglineBg: 'Понякога по-голямото е по-добро.',
    storyEn: "We took our fan-favourite Breakfast Stout and super-sized it, so there's even more to love. Creamy body, chocolate aromas and earthy hops at a warming 9.0%. Indulge.",
    storyBg: 'Взехме любимата Breakfast Stout и я увеличихме. Кремообразно тяло, шоколадови аромати и земни хмелове при загряващите 9.0%.',
    pairingEn: 'Chocolate desserts, roasted coffee, blue cheese.',
    pairingBg: 'Шоколадови десерти, препечено кафе, синьо сирене.',
    format: 'both',
    kegSizes: ['20L'],
    seasonal: false,
    active: true,
    hasLabel: true,
    labelSrc: '/labels/full-breakfast-stout.pdf',
    labelType: 'pdf',
    tags: ['unfiltered', 'unpasteurised'],
    priceB2C: 3.60,
  },
  {
    id: 'karl',
    slug: 'karl',
    name: 'Karl',
    nameBg: 'Karl',
    style: 'Session NEPA',
    styleBg: 'Сесия НЕПА',
    abv: 5.0,
    ibu: 35,
    plato: 11.5,
    ml: [500],
    serveTemp: '6–8°C',
    glass: 'Tulip',
    hops: ['Amarillo', 'Mosaic', 'Hallertau Blanc'],
    color: 'Yellow',
    accentHex: '#5BC0EB',
    contrastHex: '#0E2A66',
    displayFont: 'Resagokr',
    taglineEn: 'The familiar flavour. Less alcohol.',
    taglineBg: 'Познатият вкус. По-малко алкохол.',
    storyEn: "Lion Heart is the legend. Karl is the version that lets you have more. The same hop trio, the same aromas — but at 5.0% the body is lighter and built for longer evenings. Not a compromise. A choice.",
    storyBg: 'Lion Heart е легендата. Karl е версията, която ти позволява да имаш повече. Същото хмелово трио, същите аромати — но при 5.0% тялото е по-леко.',
    pairingEn: 'Chicken wings, light starters, margherita pizza.',
    pairingBg: 'Пилешки крилца, леки предястия, маргарита пица.',
    format: 'both',
    kegSizes: ['20L'],
    seasonal: false,
    active: true,
    hasLabel: false,
    tags: ['unfiltered', 'unpasteurised', 'vegan'],
    priceB2C: 3.00,
  },
  {
    id: 'evrozona',
    slug: 'evrozona',
    name: 'Evrozona',
    nameBg: 'Еврозона',
    style: 'Brussels Pale Ale',
    styleBg: 'Брюкселски Пейл Ейл',
    abv: 4.9,
    ibu: 25,
    plato: 10.0,
    ml: [500],
    serveTemp: '8–10°C',
    glass: 'Belgian glass',
    hops: ['Kazbek', 'Styrian Wolf', 'Magnum'],
    color: 'Golden yellow',
    accentHex: '#102050',
    contrastHex: '#F4C430',
    displayFont: 'Blogger Sans',
    taglineEn: 'Welcome to the Eurozone. At least the beer is official.',
    taglineBg: 'Добре дошли в еврозоната. Поне бирата е официална.',
    storyEn: "Brewed with Belgian yeast and European hops to mark Bulgaria's entry into the Eurozone. Moderate bitterness, grassy and lightly fruity, with a barely-there estery note from the Belgian yeast. Golden like the stars on the flag.",
    storyBg: 'Сварена с белгийска мая и европейски хмелове, за да отбележи влизането на България в еврозоната. Умерена горчивина, тревиста и леко плодова.',
    pairingEn: 'Belgian mussels, herb chicken, soft cheeses.',
    pairingBg: 'Белгийски миди, пиле с билки, меки сирена.',
    format: 'can',
    kegSizes: [],
    seasonal: false,
    active: true,
    hasLabel: true,
    labelSrc: '/labels/evrozona.png',
    labelType: 'image',
    tags: ['unfiltered', 'unpasteurised', 'vegan'],
    priceB2C: 3.20,
  },
  {
    id: 'bit',
    slug: 'bit',
    name: '.bit',
    nameBg: '.bit',
    style: 'English Best Bitter',
    styleBg: 'Английски Бест Битър',
    abv: 4.2,
    ibu: 30,
    plato: 10.9,
    ml: [500],
    serveTemp: '10–12°C',
    glass: 'Pint',
    hops: ['East Kent Golding', 'Godiva', 'Magnum'],
    color: 'Dark amber',
    accentHex: '#7A431F',
    contrastHex: '#E2A03F',
    displayFont: 'Meta',
    taglineEn: 'Earthy, honest, English. Nothing more.',
    taglineBg: 'Земен, честен, английски. Без излишно.',
    storyEn: 'English Best Bitter is the style that built British pub culture: earthy, moderately bitter, dark amber and unapologetically authentic. East Kent Golding is the classic English hop — floral, earthy, understated. A beer with character and without pretension.',
    storyBg: 'Английският Best Bitter е стилът, изградил британската пъб култура: земен, умерено горчив, тъмно кехлибарен.',
    pairingEn: 'Roast meats, beef pie, aged hard cheeses.',
    pairingBg: 'Печени меса, пай с говеждо, зрели твърди сирена.',
    format: 'both',
    kegSizes: ['20L'],
    seasonal: false,
    active: true,
    hasLabel: false,
    tags: ['unfiltered', 'unpasteurised'],
    priceB2C: 2.80,
  },
  {
    id: 'wit',
    slug: 'wit',
    name: '.wit',
    nameBg: '.wit',
    style: 'Witbier',
    styleBg: 'Витбир',
    abv: 4.7,
    ibu: 12,
    plato: 10.1,
    ml: [500],
    serveTemp: '4–6°C',
    glass: 'Wheat glass',
    hops: ['Hallertau Blanc', 'Magnum'],
    color: 'Pale golden, hazy',
    accentHex: '#E2C24E',
    contrastHex: '#5A6E2A',
    displayFont: 'Days',
    taglineEn: 'Tradition with a hop twist.',
    taglineBg: 'Традиция с хмелов обрат.',
    storyEn: 'Wheat beer is an old style. Witbier is its modern update — Hallertau Blanc adds elderflower, lime and white-wine aromas over the classic base of banana, clove and coriander. Light, hazy and surprisingly complex.',
    storyBg: 'Пшеничната бира е стар стил. Витбирът е неговото модерно обновление — Hallertau Blanc добавя бъзово цвете, лайм и аромати на бяло вино.',
    pairingEn: 'Seafood, lemon chicken, fresh salads.',
    pairingBg: 'Морски дарове, пиле с лимон, пресни салати.',
    format: 'can',
    kegSizes: [],
    seasonal: false,
    active: true,
    hasLabel: false,
    tags: ['unfiltered', 'unpasteurised', 'vegan'],
    priceB2C: 2.80,
  },
]

export interface Venue {
  id: string
  name: string
  type: 'bar' | 'restaurant' | 'bottle_shop'
  city: string
  descriptionEn: string
  descriptionBg: string
  googleMapsUrl: string
  active: boolean
}

export const venues: Venue[] = [
  {
    id: 'homs',
    name: "Hom's",
    type: 'bar',
    city: 'Sofia',
    descriptionEn: 'Craft beer bar in the heart of Sofia.',
    descriptionBg: 'Крафт бар в сърцето на София.',
    googleMapsUrl: 'https://maps.google.com',
    active: true,
  },
  {
    id: 'los-muchachos',
    name: 'Los Muchachos',
    type: 'bar',
    city: 'Sofia',
    descriptionEn: 'A favourite neighbourhood bar with a great craft beer selection.',
    descriptionBg: 'Любим квартален бар с отличен избор от крафт бири.',
    googleMapsUrl: 'https://maps.google.com',
    active: true,
  },
  {
    id: 'bar-after-5',
    name: 'Bar After 5',
    type: 'bar',
    city: 'Sofia',
    descriptionEn: 'After-hours bar with rotating taps.',
    descriptionBg: 'Следработен бар с ротиращи се кранове.',
    googleMapsUrl: 'https://maps.google.com',
    active: true,
  },
  {
    id: 'sbeerka',
    name: 'Sbeerka',
    type: 'bottle_shop',
    city: 'Sofia',
    descriptionEn: "Sofia's best craft beer bottle shop. Full Dorst range available.",
    descriptionBg: 'Най-добрият магазин за крафт бира в София. Пълна гама Dorst.',
    googleMapsUrl: 'https://maps.google.com',
    active: true,
  },
  {
    id: 'nosferatu',
    name: 'Nosferatu',
    type: 'bar',
    city: 'Sofia',
    descriptionEn: 'Dark, atmospheric bar with an excellent beer menu.',
    descriptionBg: 'Тъмен, атмосферен бар с отличен бирен мeню.',
    googleMapsUrl: 'https://maps.google.com',
    active: true,
  },
  {
    id: 'dissident',
    name: 'Dissident',
    type: 'bar',
    city: 'Sofia',
    descriptionEn: 'Independent bar championing local craft.',
    descriptionBg: 'Независим бар, шампионстващ местния крафт.',
    googleMapsUrl: 'https://maps.google.com',
    active: true,
  },
  {
    id: 'cush-bar',
    name: 'Cush Bar',
    type: 'bar',
    city: 'Sofia',
    descriptionEn: 'Relaxed bar with a carefully selected tap list.',
    descriptionBg: 'Спокоен бар с внимателно подбран списък кранове.',
    googleMapsUrl: 'https://maps.google.com',
    active: true,
  },
]

export const stats = [
  { value: '4,000', unit: 'L', label: 'Monthly production capacity' },
  { value: '20', unit: '+', label: 'Beer styles brewed' },
  { value: '10', unit: '', label: 'Beers in rotation' },
  { value: '2017', unit: '', label: 'Est. in Bankya, Bulgaria' },
]
