import { defineType, defineField, defineArrayMember } from '@sanity/types'

export const beerSchema = defineType({
  name: 'beer',
  title: 'Beer',
  type: 'document',
  fields: [
    defineField({ name: 'id',    title: 'ID (slug key)', type: 'slug', options: { source: 'name' }, validation: r => r.required() }),
    defineField({ name: 'name',  title: 'Name (EN)', type: 'string', validation: r => r.required() }),
    defineField({ name: 'nameBg', title: 'Name (BG)', type: 'string' }),
    defineField({ name: 'style',   title: 'Style (EN)', type: 'string', validation: r => r.required() }),
    defineField({ name: 'styleBg', title: 'Style (BG)', type: 'string' }),
    defineField({ name: 'abv',   title: 'ABV %',        type: 'number', validation: r => r.required().min(0).max(25) }),
    defineField({ name: 'ibu',   title: 'IBU',          type: 'number' }),
    defineField({ name: 'plato', title: 'Plato °',      type: 'number', validation: r => r.required() }),
    defineField({
      name: 'ml',
      title: 'Can sizes (ml)',
      type: 'array',
      of: [defineArrayMember({ type: 'number' })],
      validation: r => r.required().min(1),
    }),
    defineField({ name: 'serveTemp', title: 'Serve temperature',  type: 'string' }),
    defineField({ name: 'glass',     title: 'Recommended glass',  type: 'string' }),
    defineField({
      name: 'hops',
      title: 'Hops',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
    }),
    defineField({ name: 'color',       title: 'Color description', type: 'string' }),
    defineField({ name: 'accentHex',   title: 'Accent hex (label)', type: 'string' }),
    defineField({ name: 'contrastHex', title: 'Contrast hex',       type: 'string' }),
    defineField({ name: 'displayFont', title: 'Display font name',  type: 'string' }),
    defineField({ name: 'taglineEn', title: 'Tagline (EN)', type: 'string', validation: r => r.required() }),
    defineField({ name: 'taglineBg', title: 'Tagline (BG)', type: 'string' }),
    defineField({ name: 'storyEn',   title: 'Story (EN)',   type: 'text', rows: 5 }),
    defineField({ name: 'storyBg',   title: 'Story (BG)',   type: 'text', rows: 5 }),
    defineField({ name: 'pairingEn', title: 'Pairing (EN)', type: 'text', rows: 2 }),
    defineField({ name: 'pairingBg', title: 'Pairing (BG)', type: 'text', rows: 2 }),
    defineField({
      name: 'format',
      title: 'Available as',
      type: 'string',
      options: { list: ['can', 'keg', 'both'], layout: 'radio' },
      validation: r => r.required(),
    }),
    defineField({
      name: 'kegSizes',
      title: 'Keg sizes',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
    }),
    defineField({ name: 'priceB2C', title: 'B2C price (€)', type: 'number' }),
    defineField({ name: 'seasonal', title: 'Seasonal', type: 'boolean', initialValue: false }),
    defineField({ name: 'active',   title: 'Active (in rotation)', type: 'boolean', initialValue: true }),
    defineField({ name: 'hasLabel', title: 'Has printed label', type: 'boolean', initialValue: false }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [defineArrayMember({ type: 'string' })],
      options: { list: ['unfiltered', 'unpasteurised', 'vegan'] },
    }),
    defineField({
      name: 'labelImage',
      title: 'Label image',
      type: 'image',
      options: { hotspot: true },
    }),
  ],
  orderings: [
    { title: 'Name A–Z', name: 'nameAsc', by: [{ field: 'name', direction: 'asc' }] },
    { title: 'ABV high–low', name: 'abvDesc', by: [{ field: 'abv', direction: 'desc' }] },
  ],
  preview: {
    select: { title: 'name', subtitle: 'style', media: 'labelImage' },
  },
})
